/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace IVesting {
  export type UnlockEventStruct = {
    percent: BigNumberish;
    unlockTime: BigNumberish;
  };

  export type UnlockEventStructOutput = [BigNumber, BigNumber] & {
    percent: BigNumber;
    unlockTime: BigNumber;
  };
}

export interface IVestingInterface extends utils.Interface {
  contractName: "IVesting";
  functions: {
    "addBeneficiaries(address[],uint256[])": FunctionFragment;
    "addUnlockEvents(uint256[],uint256[])": FunctionFragment;
    "claimTokens()": FunctionFragment;
    "claimableAmount(address)": FunctionFragment;
    "claimablePercent()": FunctionFragment;
    "getBeneficiaries()": FunctionFragment;
    "getUnlockEvents()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addBeneficiaries",
    values: [string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "addUnlockEvents",
    values: [BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claimTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimableAmount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "claimablePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBeneficiaries",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUnlockEvents",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addBeneficiaries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addUnlockEvents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimablePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBeneficiaries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUnlockEvents",
    data: BytesLike
  ): Result;

  events: {
    "Released(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Released"): EventFragment;
}

export type ReleasedEvent = TypedEvent<
  [string, BigNumber],
  { beneficiary: string; amount: BigNumber }
>;

export type ReleasedEventFilter = TypedEventFilter<ReleasedEvent>;

export interface IVesting extends BaseContract {
  contractName: "IVesting";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IVestingInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addBeneficiaries(
      _beneficiaries: string[],
      _tokenAmounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addUnlockEvents(
      _amount: BigNumberish[],
      _unlockTime: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimTokens(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimableAmount(
      _beneficiary: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    claimablePercent(overrides?: CallOverrides): Promise<[BigNumber]>;

    getBeneficiaries(overrides?: CallOverrides): Promise<[string[]]>;

    getUnlockEvents(
      overrides?: CallOverrides
    ): Promise<[IVesting.UnlockEventStructOutput[]]>;
  };

  addBeneficiaries(
    _beneficiaries: string[],
    _tokenAmounts: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addUnlockEvents(
    _amount: BigNumberish[],
    _unlockTime: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimTokens(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimableAmount(
    _beneficiary: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  claimablePercent(overrides?: CallOverrides): Promise<BigNumber>;

  getBeneficiaries(overrides?: CallOverrides): Promise<string[]>;

  getUnlockEvents(
    overrides?: CallOverrides
  ): Promise<IVesting.UnlockEventStructOutput[]>;

  callStatic: {
    addBeneficiaries(
      _beneficiaries: string[],
      _tokenAmounts: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    addUnlockEvents(
      _amount: BigNumberish[],
      _unlockTime: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    claimTokens(overrides?: CallOverrides): Promise<void>;

    claimableAmount(
      _beneficiary: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimablePercent(overrides?: CallOverrides): Promise<BigNumber>;

    getBeneficiaries(overrides?: CallOverrides): Promise<string[]>;

    getUnlockEvents(
      overrides?: CallOverrides
    ): Promise<IVesting.UnlockEventStructOutput[]>;
  };

  filters: {
    "Released(address,uint256)"(
      beneficiary?: null,
      amount?: null
    ): ReleasedEventFilter;
    Released(beneficiary?: null, amount?: null): ReleasedEventFilter;
  };

  estimateGas: {
    addBeneficiaries(
      _beneficiaries: string[],
      _tokenAmounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addUnlockEvents(
      _amount: BigNumberish[],
      _unlockTime: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimTokens(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimableAmount(
      _beneficiary: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimablePercent(overrides?: CallOverrides): Promise<BigNumber>;

    getBeneficiaries(overrides?: CallOverrides): Promise<BigNumber>;

    getUnlockEvents(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addBeneficiaries(
      _beneficiaries: string[],
      _tokenAmounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addUnlockEvents(
      _amount: BigNumberish[],
      _unlockTime: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimTokens(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimableAmount(
      _beneficiary: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claimablePercent(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getBeneficiaries(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getUnlockEvents(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
